# Generated by Django 4.2.1 on 2023-07-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lunch_Menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='foodType',
            field=models.CharField(default=2345678, max_length=100),
            preserve_default=False,
        ),
    ]
