# Generated by Django 4.2.3 on 2023-08-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lunch_Menu', '0005_alter_fooditem_foodtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='foodType',
            field=models.CharField(choices=[('food', 'Food'), ('sauces', 'Sauces'), ('extra', 'Extras')], max_length=100, null=True),
        ),
    ]
