# Generated by Django 4.2.1 on 2023-08-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lunch_Menu', '0007_alter_fooditem_foodtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunchorder',
            name='time_of_order',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
