# Generated by Django 4.2.3 on 2023-08-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lunch_Menu', '0007_alter_fooditem_foodtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
