# Generated by Django 4.2.1 on 2023-08-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lunch_Menu', '0008_lunchorder_time_of_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunchorder',
            name='time_of_order',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
