# Generated by Django 4.2.3 on 2023-08-10 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lunch_Menu', '0008_fooditem_is_active'),
        ('Lunch_Menu', '0009_alter_lunchorder_time_of_order'),
    ]

    operations = [
    ]
